=== QiwSam/toptout/schema/toptout.schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/Toptout",
    "definitions": {
        "Toptout": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "category": {
                    "type": "string"
                },
                "links": {
                    "$ref": "#/definitions/ToptoutLinks"
                },
                "telemetry": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Telemetry"
                    }
                }
            },
            "required": [
                "description",
                "category",
                "id",
                "links",
                "name"
            ],
            "title": "Toptout"
        },
        "ToptoutLinks": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "main": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "telemetry": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                },
                "privacy": {
                    "type": "string",
                    "format": "uri",
                    "qt-uri-protocols": [
                        "https"
                    ]
                }
            },
            "required": [
                "main"
            ],
            "title": "ToptoutLinks"
        },
        "Telemetry": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "links": {
                    "$ref": "#/definitions/ToptoutLinks"
                },
                "target": {
                    "$ref": "#/definitions/Target"
                }
            },
            "required": [
                "id",
                "name"
            ],
            "title": "Telemetry"
        },
        "Target": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "json_file": {
                    "$ref": "#/definitions/JSONFile"
                },
                "exec": {
                    "$ref": "#/definitions/Exec"
                },
                "env": {
                    "$ref": "#/definitions/Env"
                },
                "plain_file": {
                    "$ref": "#/definitions/PlainFile"
                }
            },
            "anyOf": [
                {
                    "required": [
                        "json_file"
                    ]
                },
                {
                    "required": [
                        "exec"
                    ]
                },
                {
                    "required": [
                        "env"
                    ]
                },
                {
                    "required": [
                        "plain_file"
                    ]
                }
            ],
            "required": [],
            "title": "Target"
        },
        "Env": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "path": {
                    "$ref": "#/definitions/Path"
                },
                "value": {
                    "$ref": "#/definitions/Value"
                }
            },
            "required": [
                "path",
                "value"
            ],
            "title": "Env"
        },
        "Exec": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "path": {
                    "$ref": "#/definitions/Path"
                },
                "value": {
                    "$ref": "#/definitions/Value"
                }
            },
            "required": [
                "path",
                "value"
            ],
            "title": "Env"
        },
        "Value": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "opt_out": {
                    "type": "string"
                },
                "opt_in": {
                    "type": [
                        "string",
                        "null"
                    ]
                }
            },
            "required": [
                "opt_in",
                "opt_out"
            ],
            "title": "Value"
        },
        "JSONFile": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "path": {
                    "$ref": "#/definitions/Path"
                },
                "selector": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/Value"
                },
                "display_value": {
                    "type": "string"
                }
            },
            "required": [
                "display_value",
                "path",
                "selector",
                "value"
            ],
            "title": "JSONFile"
        },
        "PlainFile": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "path": {
                    "$ref": "#/definitions/Path"
                },
                "selector": {
                    "type": "string"
                },
                "value": {
                    "$ref": "#/definitions/Value"
                },
                "display_value": {
                    "type": "string"
                }
            },
            "required": [
                "display_value",
                "path",
                "selector",
                "value"
            ],
            "title": "PlainFile"
        },
        "Path": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "linux": {
                    "type": "string"
                },
                "macos": {
                    "type": "string"
                },
                "windows": {
                    "type": "string"
                },
                "default": {
                    "type": "string"
                }
            },
            "anyOf": [
                {
                    "required": [
                        "default"
                    ]
                },
                {
                    "required": [
                        "linux"
                    ]
                },
                {
                    "required": [
                        "macos"
                    ]
                },
                {
                    "required": [
                        "windows"
                    ]
                }
            ],
            "title": "Path"
        }
    }
}

=== QiwSam/toptout/data/gatsby-js.json
{
  "id": "gatsby-js",
  "name": "Gatsby",
  "category": "Development tools",
  "description": "Gatsby contains a telemetry feature that collects anonymous usage information that is used to help improve Gatsby for all users. The Gatsby user base is growing very rapidly. Itâ€™s important that our small team and the greater community will better understand the usage patterns, so we can best decide how to design future features and prioritize current work.",
  "links": {
    "main": "https://www.gatsbyjs.org",
    "telemetry": "https://www.gatsbyjs.org/docs/telemetry/",
    "privacy": "https://www.gatsbyjs.com/privacy-policy/"
  },
  "telemetry": [
    {
      "id": "usage-data",
      "name": "Usage data",
      "target": {
        "env": {
          "path": {
            "default": "GATSBY_TELEMETRY_DISABLED"
          },
          "value": {
            "opt_out": "1",
            "opt_in": "0"
          }
        },
        "exec": {
          "path": {
            "default": "gatsby"
          },
          "value": {
            "opt_out": "telemetry --disable",
            "opt_in": "telemetry --enable"
          }
        }
      }
    }
  ]
}

=== QiwSam/toptout/data/automated-lab.json
{
  "id": "automated-lab",
  "name": "AutomatedLab",
  "category": "Development tools",
  "description": "AutomatedLab will start to collect telemetry starting with version 5.0. This is an opt-out collection and you will be asked once to specify whether or not you want to send us telemetry data.",
  "links": {
    "main": "https://github.com/AutomatedLab/AutomatedLab",
    "telemetry": "https://github.com/AutomatedLab/AutomatedLab/wiki/Lab-Telemetry"
  },
  "telemetry": [
    {
      "id": "usage-data",
      "name": "Usage data",
      "target": {
        "env": {
          "path": {
            "default": "AUTOMATEDLAB_TELEMETRY_OPTOUT"
          },
          "value": {
            "opt_out": "1",
            "opt_in": "0"
          }
        },
        "exec": {
          "path": {
            "default": "pwsh",
            "windows": "powershell"
          },
          "value": {
            "opt_out": "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command \"Import-Module AutomatedLab -ErrorAction Stop ; Disable-LabTelemetry -ErrorAction Stop\"",
            "opt_in": "-NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -Command \"Import-Module AutomatedLab -ErrorAction Stop ; Enable-LabTelemetry -ErrorAction Stop\""
          }
        }
      }
    }
  ]
}

=== QiwSam/toptout/data/microsoft-calculator.json
{
  "id": "microsoft-calculator",
  "name": "Microsoft calculator",
  "category": "Applications",
  "description": "This project collects usage data and sends it to Microsoft to help improve our products and services. Diagnostic data is disabled in development builds by default, and can be enabled with the SEND_DIAGNOSTICS build flag.",
  "links": {
    "main": "https://github.com/Microsoft/calculator",
    "telemetry": "https://github.com/microsoft/calculator#diagnostic-data",
    "privacy": "https://go.microsoft.com/fwlink/?LinkId=521839"
  }
}

=== QiwSam/toptout/data/cordova-cli.json
{
  "id": "cordova-cli",
  "name": "Apache Cordova CLI",
  "category": "Development tools",
  "description": "We use the gathered information to help us make our tool more useful and to better understand how it is used. We do not track or collect personally identifiable information or associate gathered data with any personally identifying information from other sources.",
  "links": {
    "main": "https://cordova.apache.org",
    "telemetry": "https://cordova.apache.org/docs/en/latest/reference/cordova-cli/#global-command-list",
    "privacy": "https://cordova.apache.org/privacy/"
  },
  "telemetry": [
    {
      "id": "usage-data",
      "name": "Usage data",
      "target": {
        "env": {
          "path": {
            "default": "CI"
          },
          "value": {
            "opt_out": "ANY_VALUE",
            "opt_in": null
          }
        },
        "exec": {
          "path": {
            "default": "cordova"
          },
          "value": {
            "opt_out": "telemetry off",
            "opt_in": "telemetry off"
          }
        }
      }
    }
  ]
}
